<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Trofaco_Frontent</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>60cbdeeb-a484-4e13-aa23-f7f36223592c</testSuiteGuid>
   <testCaseLink>
      <guid>accbaf8a-2ae2-4e93-96f2-d89ce85b4440</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Frontend_ThumbnailSize86OnMap</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57bd873c-f606-46fe-9b61-74d81f6129b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a20c71f-1662-4340-b42a-4c00395340f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df9e1ee5-907a-44e3-86bf-7bad5e9212ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Frontend_Availabletrees</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6914d339-312b-400e-9e15-3bc081682489</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63dd2267-a118-42e2-92a4-7c6c6235a9c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70bbea24-55a2-4650-9e56-fd280f317966</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Frontend_PlantTreesButton</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d421ec0-94fb-4cae-8fac-b4a153bdabfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21095f44-b184-4da1-b343-6dbe19541d68</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
