<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Labels_icon-prev carousel-control-prev-icon</name>
   <tag></tag>
   <elementGuidId>ed182240-7fbe-46c0-b3f2-9ffca52f6617</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-collection-dialog/div/div/div/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-prev carousel-control-prev-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;frontend sidebar-hidden aside-menu-hidden header-fixed ng-tns-0-0 modal-open&quot;]/app-root[@class=&quot;active&quot;]/app-frontend[1]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container&quot;]/app-collection-detail[1]/app-collection-dialog[1]/div[@class=&quot;modal fade modal-full-screen-img in show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;align-items-center active item carousel-item&quot;]/a[@class=&quot;left carousel-control carousel-control-prev&quot;]/span[@class=&quot;icon-prev carousel-control-prev-icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-collection-dialog/div/div/div/div/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
